### ISSUE TITLE
PPT 출력하는법에 대해

### ISSUE THREAD

**Issue by Syracusa** [jamsya/Ue4VrProject#7]
![ppt](https://user-images.githubusercontent.com/23725976/46943919-b89bbf80-d0ab-11e8-906a-56986407989f.png)

PPT를 언리얼에서 출력하는 법에 대해 여러모로 고민해봤는데

PPT를 직접 업로드해서 이미지파일로 변환해 텍스쳐로 입히거나 하는건 어려울거같아서

웹 브라우져 플러그인을 이용하여 웹화면을 띄우고 웹에 미리 올려놓은 ppt를 띄우는 방법으로 해봤습니다. 

조작방법이나 화질같은건 더 봐야될거같긴 한데 이 방법으로 해도 괜찮지 않을까요?

참고한 웹브라우져 플러그인 사용 튜토리얼 - https://www.youtube.com/watch?v=ODvbDVZ2AOc

-기진

**Comment by ryrie** [comment]
rumii같은경우에는 pdf까지는 되는데 ppt는 없네요 언리얼에서 볼수있는 플러그인이 있으면 되지않을까 싶은데 정 안되면 저렇게 해야죠 -종석
